modLoader="neoforge"
loaderVersion="[2,)" # Compatible avec la version actuelle de NeoForge
license="MIT"

[[mods]]
modId="skilltree"
version="1.0.0"
displayName="Skilltree"
authors="TonNom"
description='''
Mod d'arbre de talents passifs pour Minecraft 1.21.1 basé sur un système de runes, avec une progression par niveaux et des effets uniques.
'''

[[dependencies.skilltree]]
modId="neoforge"
type="required"
versionRange="[20.4.123,)" # Remplace ce numéro si tu utilises une autre version exacte
ordering="NONE"
side="BOTH"

[[dependencies.skilltree]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
